-- Generated by nwg-displays on 2026-05-22 at 09:16:05. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@240.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@143.98",
    position = "2560x0",
    scale = 1.0
})
